version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-test:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: rm -rf lib && node_modules/.bin/tsc -b
                      - run: npm test
                      - run: npm run lint
workflows:
    build-and-test:
        jobs:
            - build-and-test
